### ISSUE TITLE
How can I use the latest nncase library in kendryte-standalone-sdk ?

### ISSUE THREAD

**Issue by BOGUENSONG** [kendryte/kendryte-standalone-sdk#126]
Hello guys.

I use nncase Command Line Tools 1.0.0-52d9bfa for convert my custom ONNX model

and I successfully converted my model  and test on my desktop also clear. 

but when i use latest kendryte-standalone-sdk for test in my k210 device, 
test was failed. (in kpu_run_kmodel, state become blocked )

is this problem due to a nncase version difference ? 

if so, how can i use latest nncase library in kendryte-standalone-sdk ?

Should I just wait for your updates ? 

Thank you.

**Comment by sunnycase** [comment]
Unzip `runtime-k210.zip` to `sdk/lib/nncase/v1`

**Comment by BOGUENSONG** [comment]
Thank you !! :)

**Comment by Qinka** [comment]
> Unzip `runtime-k210.zip` to `sdk/lib/nncase/v1`

I think you should add this "how to" into nncase's readme or document of usage
