### ISSUE TITLE
无法使用kflash将代码烧录到开发板上

### ISSUE THREAD

**Issue by Reihold-Chen** [kendryte/kendryte-standalone-sdk#131]
> BUG REPORT

### toolchain version

standalone SDK 0.5.6
kflash V1.6

### Hardware

Maix DOCK

### problem

在烧写代码时, kflash提示如下错误:
![image](https://user-images.githubusercontent.com/57242405/136808886-1a7b56ac-3322-4453-99a6-42dbd844eca5.png)
kflash配置如下:
![image](https://user-images.githubusercontent.com/57242405/136809102-e23314d5-4b0e-4381-a1d3-c72590e38295.png)

但是我用 maixpy IDE 时, 下载功能是正常的, 说明连接没有问题.

不只是是否有人遇到过这个问题

**Comment by zhen8838** [comment]
你可以试试直接使用kflash.py

**Comment by Reihold-Chen** [comment]
可用的解决办法:
- 安装kflash
```
python -m pip install kflash
``` 
- 检查是否安装成功
```
pip list

kflash             1.0.2 #出现 代表安装成功
```

 - 使用kflash下载, 到bin文件目录
 ```python -m kflash -B dan hello_world.bin```
