### ISSUE TITLE
How can I use nncase with kendryte-standalone-sdk?

### ISSUE THREAD

**Issue by xu-yingjing** [kendryte/kendryte-standalone-sdk#139]
Hello
I don't know how to use nncase(v1.9.0, the last version support K210) in kendryte-standalone-sdk(V0.5.6 or V0.5.7, the release version, not the develop branch)
I try to follow the USAGE_ZH.md in nncase to copy nncase runtime to kendryte-standalone-sdk's lib/nncase/v1 directory, but it have no such directory or directory structure in kendryte-standalone-sdk
How can I use nncase with kendryte-standalone-sdk
Thank you

**Comment by zhen8838** [comment]
The `nncase` 1.x only compatible with `kendryte-standalone-sdk` develop branch.

**Comment by xu-yingjing** [comment]
Thank you for your reply!😄
