### ISSUE TITLE
Some Error in uarths.h: redeclaration of enumerator 'UART_STOP_1'

### ISSUE THREAD

**Issue by YXZhu** [kendryte/kendryte-standalone-sdk#28]
![image](https://user-images.githubusercontent.com/24542191/48664011-3b60d180-ead3-11e8-854c-5ab7770c4de1.png)

**Comment by vowstar** [comment]
Which version of SDK do you use?
Could you try SDK https://github.com/kendryte/kendryte-standalone-sdk/releases/tag/v0.5.2?

**Comment by YXZhu** [comment]
I found its fixed ,Thanks

**Comment by YXZhu** [comment]
I found its fixed ,Thanks
