### ISSUE TITLE
Open DVP_CMOS_CLK_DIV settings so you can lower the DVP Clock speed.

### ISSUE THREAD

**Issue by jimaobian** [kendryte/kendryte-standalone-sdk#32]
https://github.com/kendryte/kendryte-standalone-sdk/blob/2cfcee428b2504da430f717afe28311d858d13f8/lib/drivers/dvp.c#L143

Some camera cannot reach high speed parallel communication.

**Comment by zzxcanaan** [comment]
You can use dvp_set_xclk_rate to set xclk rate.

**Comment by jimaobian** [comment]
Thank you!
