### ISSUE TITLE
develop branch vs kendryte-freertos-sdk repository

### ISSUE THREAD

**Issue by loboris** [kendryte/kendryte-standalone-sdk#34]
I'm confused about **develop** branch in this repository (which looks to be the freertos sdk actually) compared to **kendryte-freertos-sdk** repository.
Could you, please, explain what are the differences and why are there two repositories containing freertos?

**Comment by zzxcanaan** [comment]
We have deleted freertos.

**Comment by loboris** [comment]
Thanks, it is much cleaner now.
