### ISSUE TITLE
plic_irq_callback_t return value

### ISSUE THREAD

**Issue by michprev** [kendryte/kendryte-standalone-sdk#47]
https://github.com/kendryte/kendryte-standalone-sdk/blob/180eb33c6cbe3c55b6df9a55ba2f164253a85542/lib/drivers/include/plic.h#L356-L359

IRQ callback should return `int` but the value does not seem to be used anywhere.
https://github.com/kendryte/kendryte-standalone-sdk/blob/180eb33c6cbe3c55b6df9a55ba2f164253a85542/lib/drivers/plic.c#L195-L196

Are there any future plans to use this return value? Otherwise it might be better to change it to `void` to avoid confusion.

**Comment by zzxcanaan** [comment]
We will use the return value to determine whether the execution is correct
