### ISSUE TITLE
lib/drivers/dvp.c configASSERT error

### ISSUE THREAD

**Issue by xelll** [kendryte/kendryte-standalone-sdk#5]
in function 

void dvp_set_output_enable(dvp_output_mode_t index, int enable)
{
    // configASSERT(index < 2);

    if (index == 0)
    {
        if (enable)
            dvp->dvp_cfg |= DVP_CFG_AI_OUTPUT_ENABLE;
        else
            dvp->dvp_cfg &= ~DVP_CFG_AI_OUTPUT_ENABLE;
    }
    else
    {
        if (enable)
            dvp->dvp_cfg |= DVP_CFG_DISPLAY_OUTPUT_ENABLE;
        else
            dvp->dvp_cfg &= ~DVP_CFG_DISPLAY_OUTPUT_ENABLE;
    }
}
i call it as 
dvp_set_output_enable(DVP_CFG_AI_OUTPUT_ENABLE | DVP_CFG_DISPLAY_OUTPUT_ENABLE,1);

but the configASSERT is error.

**Comment by sunnycase** [comment]
The first argument should be a `dvp_output_mode_t`
```c
typedef enum _dvp_output_mode
{
    DVP_OUTPUT_AI,
    DVP_OUTPUT_DISPLAY,
} dvp_output_mode_t;
```
You should pass either `DVP_OUTPUT_AI` or `DVP_OUTPUT_DISPLAY` instead of `DVP_CFG_AI_OUTPUT_ENABLE | DVP_CFG_DISPLAY_OUTPUT_ENABLE`.
