### ISSUE TITLE
small error in README.md

### ISSUE THREAD

**Issue by GitJer** [kendryte/kendryte-standalone-sdk#59]
In the README.md the following line appears:
`cmake .. -DPROJ=<ProjectName> -DTOOLCHAIN=/opt/riscv-toolchain/bin && make`

but then it cannot find CMakeLists.txt. What the line should be (at least it then works for me) is:
`cmake ../.. -DPROJ=<ProjectName> -DTOOLCHAIN=/opt/riscv-toolchain/bin && make`

So, cmake should start one directory higher.

**Comment by zzxcanaan** [comment]
You should mkdir build in SDK root directory,then cd build.
cmake .. -DPROJ=<ProjectName> -DTOOLCHAIN=/opt/riscv-toolchain/bin && make
