### ISSUE TITLE
Double precision floating point support

### ISSUE THREAD

**Issue by SiliconWizard** [kendryte/kendryte-standalone-sdk#71]
Hello, the D extension is currently not enabled in the standalone SDK. It looks like there has been some going back and forth about it in past revisions.

Why is it so? Is double-precision FP in the K210 buggy or is it because of a GCC bug? Could you please document that? Knowing whether double-precision FP is usable or not in the K210 is fairly important.

I have enabled it and done some basic testing and there doesn't seem to be a problem, but I haven't tested double-precision FP extensively so far...

**Comment by redchenjs** [comment]
Also want to know...
