### ISSUE TITLE
plic_irq_enable() should be always followed by plic_irq_register()

### ISSUE THREAD

**Issue by jimaobian** [kendryte/kendryte-standalone-sdk#78]
https://github.com/kendryte/kendryte-standalone-sdk/blob/d45f50d9fabe02379a1149dca5c1910913301a1f/lib/drivers/dmac.c#L777

Interrupt may be occurred by running the null or old callback.

**Comment by zzxcanaan** [comment]
So you should set the callback of dma.

**Comment by jimaobian** [comment]
![image](https://user-images.githubusercontent.com/3905677/57676246-ab04e300-7656-11e9-8910-1f38fe40197c.png)
Reverse Line 777 and Line 778. And review all the example about this problem.
