### ISSUE TITLE
must i set some io as chip_select?

### ISSUE THREAD

**Issue by xelll** [kendryte/kendryte-standalone-sdk#79]
https://github.com/kendryte/kendryte-standalone-sdk/blob/74bb90431969c55d83ce4fa2e6cd087a152b6153/lib/drivers/spi.c#L684

must i set some io as spix chip_select? if i didnot use hardware cs, how to use?

**Comment by Pillar1989** [comment]
Indeed so, it would be nice to have a `is_use_chip_select` option.

**Comment by zzxcanaan** [comment]
You don't need to set io as spi cs. But you should set chip_select when using spi api.

**Comment by xelll** [comment]
> You don't need to set io as spi cs. But you should set chip_select when using spi api.

ok
