### ISSUE TITLE
执行 cmake ..-DPROJ=hello_world -G "MinGW Makefiles"没反应

### ISSUE THREAD

**Issue by Danielhui** [kendryte/kendryte-standalone-sdk#93]
Make sure you read and understand this document.
Use one of the two templates below and delete the rest.

- [ ] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT
PS D:\kendryte-standalone-sdk-0.5.6\build> cmake ..-DPROJ=hello_world -G "MinGW Makefiles"
CMake Error: The source directory "D:/kendryte-standalone-sdk-0.5.6/build/..-DPROJ=hello_world" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
PS D:\kendryte-standalone-sdk-0.5.6\build> 

Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

按照指南一步步执行到这执行不下去了

**Comment by minux** [comment]
.. 和 -DPROJ=hello_world 之间应该有一个空格。

cmake .. -DPROJ=hello_world -G "MinGW Makefiles"
